name: Deploy React App to GitHub Pages

# Trigger the workflow on push to the main branch and allow manual trigger from the Actions tab
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Set concurrency to ensure only one deployment is happening at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or the version you're using in your project

      # Step 3: Install dependencies (install all packages without uploading node_modules)
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app for production
      - name: Build the project
        run: npm run build

      # Step 5: Upload artifact (the build folder that contains the optimized production files)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # This is where the production build will be located

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      # Step 6: Deploy the build folder to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
